services:
  java:
    image: ghcr.io/bertrik/stofradar
    build: ..
    restart: always
    volumes:
      - "./stofradar.yaml:/opt/stofradar/stofradar.yaml:ro"
      - "./www:/opt/stofradar/www:rw"
